#!/usr/bin/bash
qemu-system-riscv64 \
-bios build/bin \
-M virt \
-m 512M \
-device bochs-display \
-device virtio-keyboard-pci \
-drive file=res/hd0.img,if=none,format=raw,id=hd0 \
-device virtio-blk-pci,drive=hd0 \
-monitor  stdio
